# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Trade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Trade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bTrade.proto\x12\x0c\x66ixprocessor\"\x8c\x01\n\x05Trade\x12+\n\tnew_order\x18\x01 \x01(\x0b\x32\x16.fixprocessor.NewOrderH\x00\x12&\n\x06\x63\x61ncel\x18\x02 \x01(\x0b\x32\x14.fixprocessor.CancelH\x00\x12$\n\x05\x61mend\x18\x03 \x01(\x0b\x32\x13.fixprocessor.AmendH\x00\x42\x08\n\x06\x61\x63tion\"M\n\x08NewOrder\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"\x1a\n\x06\x43\x61ncel\x12\x10\n\x08order_id\x18\x01 \x01(\t\"B\n\x05\x41mend\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0cnew_quantity\x18\x02 \x01(\x05\x12\x11\n\tnew_price\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Trade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_TRADE']._serialized_start = 30
    _globals['_TRADE']._serialized_end = 170
    _globals['_NEWORDER']._serialized_start = 172
    _globals['_NEWORDER']._serialized_end = 249
    _globals['_CANCEL']._serialized_start = 251
    _globals['_CANCEL']._serialized_end = 277
    _globals['_AMEND']._serialized_start = 279
    _globals['_AMEND']._serialized_end = 345
# @@protoc_insertion_point(module_scope)
